#!/bin/bash
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 5000 --warmup_steps 200 --log_interval 100 --val_interval 250 --batch_size 256 --learning_rate 0.01 --save_path checkpoints/bs_256.pt --run_name 'bs=256'
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 10000 --warmup_steps 400 --log_interval 100 --val_interval 500 --batch_size 128 --learning_rate 0.01 --save_path checkpoints/bs_128.pt --run_name 'bs=128'
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 20000 --warmup_steps 800 --log_interval 200 --val_interval 1000 --batch_size 64 --learning_rate 0.01 --save_path checkpoints/bs_64.pt --run_name 'bs=64'
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 40000 --warmup_steps 1600 --log_interval 400 --val_interval 2000 --batch_size 32 --learning_rate 0.01 --save_path checkpoints/bs_32.pt --run_name 'bs=32'
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 80000 --warmup_steps 3200 --log_interval 800 --val_interval 4000 --batch_size 16 --learning_rate 0.01 --save_path checkpoints/bs_16.pt --run_name 'bs=16'
# too small batch size, so lower learning rate
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 80000 --warmup_steps 3200 --log_interval 800 --val_interval 4000 --batch_size 4 --learning_rate 0.0001 --save_path checkpoints/bs_4.pt --run_name 'bs=4'
python cs336_basics/train.py --train_data ./data/tiny_stories_train_tokens.npy --val_data data/tiny_stories_valid_tokens.npy --total_steps 80000 --warmup_steps 3200 --log_interval 800 --val_interval 4000 --batch_size 1 --learning_rate 0.0001 --save_path checkpoints/bs_1.pt --run_name 'bs=1'
